---
openapi: 3.0.3
info:
  title: Order API
  description: API para gestión de órdenes en el e-commerce.
  version: 1.0.0
servers:
  - url: https://r36c7jyp0b.execute-api.us-east-1.amazonaws.com/dev/api
paths:
  /order:
    get:
      summary: Obtener una orden por ID
      description: Devuelve el detalle de una orden dada por UserId y OrderId.
      tags:
        - Orders
      parameters:
        - name: userid
          in: query
          required: true
          schema:
            type: string
            example: e6ceb306-a3d3-4597-9751-936c9ca5d476
        - name: orderid
          in: query
          required: true
          schema:
            type: string
            example: ov-16dc90bc
      responses:
        "200":
          description: Información de la orden
          content:
            application/json:
              schema:
                type: object
                properties:
                  Status:
                    type: integer
                  Message:
                    type: string
                  Data:
                    $ref: "#/components/schemas/Order"
              example:
                Status: 200
                Message: Se ha obtenido la información satisfactoriamente
                Data:
                  UserId: e6ceb306-a3d3-4597-9751-936c9ca5d476
                  OrderId: ov-16dc90bc
                  Address:
                    Reference: ""
                    Country: Perú
                    Default: true
                    City: Pueblo Libre
                    Location:
                      Lat: -12.190071
                      Lon: -77.054553
                    State: Lima
                    Type: home
                    Line1: Calle La Molina 305
                    Line2: ""
                  CreatedAt: 2025-05-03T06:10:40.699854+00:00
                  DeliveredAt: 2025-05-03T06:10:40.699854+00:00
                  DeliveryRating: 3
                  DeliveryStartedAt: 2025-05-03T06:10:40.699868+00:00
                  Items:
                    - SkuId: GPU-AMD-RADEONRX6800
                      Price: 3999
                      Quantity: 3
                  Notes: Tocar el timbre
                  PaidAt: 2025-05-03T06:10:40.699861+00:00
                  PaymentMethod: tarjeta
                  Status: delivered
                  StoreId: sanisidro1
                  TotalAmount: 23441
                  TrackingStatus: delivered
        "400":
          description: Faltan parámetros obligatorios
          content:
            application/json:
              schema:
                type: object
                properties:
                  Status:
                    type: integer
                    example: 400
                  Message:
                    type: string
                    example: Faltan parámetros obligatorios userid y orderid
                  Data:
                    type: string
                    example: null
        "401":
          description: Token inválido o no proporcionado
          content:
            application/json:
              schema:
                type: object
                properties:
                  Status:
                    type: integer
                    example: 401
                  Message:
                    type: string
                    example: Token inválido o no proporcionado
                  Data:
                    type: string
                    example: null
      security:
        - bearerAuth: []
    post:
      summary: Crear una orden
      description: Crea una nueva orden.
      tags:
        - Orders     
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/OrderRequest"
      responses:
        "200":
          description: Registro exitoso
          content:
            application/json:
              schema:
                type: object
                properties:
                  Status:
                    type: integer
                    example: 200
                  Message:
                    type: string
                    example: El registro se realizó exitosamente
                  Data:
                    type: object
                    properties:
                      OrderId:
                        type: string
                        example: c2e2b09d-ed1e-4710-8d62-31f7aba9f154
        "400":
          description: Error en el body
          content:
            application/json:
              schema:
                type: object
                properties:
                  Status:
                    type: integer
                  Message:
                    type: string
                  Data:
                    type: string
      security:
        - bearerAuth: []
    put:
      summary: Actualizar una orden
      description: Actualiza una orden existente.
      tags:
        - Orders
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/OrderUpdateRequest"
      responses:
        "200":
          description: Actualización exitosa
          content:
            application/json:
              schema:
                type: object
                properties:
                  Status:
                    type: integer
                    example: 200
                  Message:
                    type: string
                    example: Se actualizado el registro exitosamente
                  Data:
                    type: object
                    properties:
                      OrderId:
                        type: string
                        example: ov-ce633115
      security:
        - bearerAuth: []
    delete:
      summary: Eliminar una orden
      description: Elimina una orden dada por UserId y OrderId.
      tags:
        - Orders
      parameters:
        - name: userid
          in: query
          required: true
          schema:
            type: string
            example: 2cd71ae7-725a-4fa7-9d87-8f5a13413e41
        - name: orderid
          in: query
          required: true
          schema:
            type: string
            example: ov-ce633115
      responses:
        "200":
          description: Eliminación exitosa
          content:
            application/json:
              schema:
                type: object
                properties:
                  Status:
                    type: integer
                    example: 200
                  Message:
                    type: string
                    example: Se eliminado el registro satisfactoriamente
                  Data:
                    type: object
                    properties:
                      OrderId:
                        type: string
                        example: ov-ce633115
      security:
        - bearerAuth: []
    options:
      summary: Respuesta CORS preflight
      description: Responde a preflight requests con los headers necesarios para CORS.
      tags:
        - Orders
      responses:
        "200":
          description: Respuesta para preflight CORS
          headers:
            Access-Control-Allow-Origin:
              schema:
                type: string
                example: "*"
            Access-Control-Allow-Methods:
              schema:
                type: string
                example: GET, POST, PUT, DELETE, OPTIONS
            Access-Control-Allow-Headers:
              schema:
                type: string
                example: Content-Type, Authorization
          content:
            application/json:
              schema:
                type: string
                example: ""
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:
    Order:
      type: object
      properties:
        UserId:
          type: string
        OrderId:
          type: string
        Address:
          $ref: "#/components/schemas/OrderAddress"
        CreatedAt:
          type: string
          format: date-time
        DeliveredAt:
          type: string
          format: date-time
        DeliveryRating:
          type: integer
        DeliveryStartedAt:
          type: string
          format: date-time
        Items:
          type: array
          items:
            $ref: "#/components/schemas/OrderItem"
        Notes:
          type: string
        PaidAt:
          type: string
          format: date-time
        PaymentMethod:
          type: string
        Status:
          type: string
        StoreId:
          type: string
        TotalAmount:
          type: number
        TrackingStatus:
          type: string
    OrderAddress:
      type: object
      properties:
        Reference:
          type: string
        Country:
          type: string
        Default:
          type: boolean
        City:
          type: string
        Location:
          type: object
          properties:
            Lat:
              type: number
            Lon:
              type: number
        State:
          type: string
        Type:
          type: string
        Line1:
          type: string
        Line2:
          type: string
    OrderItem:
      type: object
      properties:
        SkuId:
          type: string
        Price:
          type: number
        Quantity:
          type: integer
    OrderRequest:
      allOf:
        - $ref: "#/components/schemas/Order"
        - type: object
          required:
            - UserId
            - Address
            - CreatedAt
            - Items
            - PaymentMethod
            - Status
            - StoreId
            - TotalAmount
            - TrackingStatus
    OrderUpdateRequest:
      allOf:
        - $ref: "#/components/schemas/Order"
        - type: object
          required:
            - UserId
            - OrderId
            - Address
            - CreatedAt
            - Items
            - PaymentMethod
            - Status
            - StoreId
            - TotalAmount
            - TrackingStatus